### PR TITLE
New testing

### PR DESCRIPTION
**Pull request by moizkkiller123**
my game crashes when i try to go ingame

### CODE REVIEW

**Comment by retart1337** [comment]
@TheFuckingRat

**Comment by retart1337** [comment]
Report bug in discord, please

**Comment by moizkkiller123** [comment]
> Report bug in discord, please

what happened to old discord server

**Comment by siautalius** [comment]
got deleted

**Comment by moizkkiller123** [comment]
> got deleted

but how

**Comment by siautalius** [comment]
probably broke discords ToS

**Pull request closed without merging**
