### PR TITLE
Get dwbSendPackets offset from github

### PR DESCRIPTION
**Pull request by retart1337**

### CODE REVIEW

**Comment by sotakoira** [comment]
guys i think this will download a virus now

**Comment by wuba1337** [comment]
> guys i think this will download a virus now

it is only loading a json config file with netvars and signatures?

**Comment by retart1337** [comment]
help!! ratto ratted my pc

**Comment by sotakoira** [comment]
help cheat doesnt let me launch because cant connect to github? is this drm or what??

**Pull request merged**
