### PR TITLE
Make localization possible

### PR DESCRIPTION
**Pull request by retart1337**

### CODE REVIEW

**Comment by matt1tk** [comment]
This changes the JDK from 13 to 12, have you tested it to see if it still works?

**Comment by retart1337** [comment]
Yes, i have tested

**Comment by matt1tk** [comment]
Why is this changed? https://github.com/TheFuckingRat/RatPoison/pull/421/files#diff-709b322d95fc15d5133c5478adb47c6c Just wondering since the default install is JDK 13.

Also, thanks so much for this work. asking ratto if I can merge to beta right now

**Comment by retart1337** [comment]
idk i was debugging rp with coverage and this changed

**Pull request merged**
