### PR TITLE
inferno nade helper

### PR DESCRIPTION
**Pull request by dayz2000**
[inferno.txt](https://github.com/TheFuckingRat/RatPoison/files/5006940/inferno.txt)

### CODE REVIEW

**Comment by sotakoira** [comment]
what the fuck is going on

**Comment by thefuckingrap** [comment]
my friend

**Comment by TheFuckingRat** [comment]
no.

**Comment by retart1337** [comment]
Matt please merge

**Comment by thefuckingrap** [comment]
stfu!!!

**Pull request closed without merging**
