### PR TITLE
what happened to the discord server?

### PR DESCRIPTION
**Pull request by JagodekSTREAM**
?

### CODE REVIEW

**Comment by sotakoira** [comment]
banned by discord moderators, just join the new one. updated links are already in rp just redownload

**Comment by thefuckingrap** [comment]
we banned you

**Comment by retart1337** [comment]
I will fucking beat you up

**Comment by thefuckingrap** [comment]
> 
> 
> I will fucking beat you up

umad

**Comment by siautalius** [comment]
lol im in github updates

**Pull request closed without merging**
